name: "Add Labels v2"
description: "Add labels on Pull Requests or Issues"
inputs:
  issue_number:
    required: true
  labels:
    description: "Labels to add"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "plus"
  color: "blue"
